hiero-ledger/governance

- config.yaml
First step for https://github.com/LFDT-Hiero/website/issues/12
> website repo commented out

- config.yaml
See https://github.com/hashgraph/hedera-services/issues/14255
> chore: add 'hiero-gradle-conventions' repository

- config.yaml
Add maintainers and committers groups for `hiero-block-node`
> Add hiero-block-node groups

- config.yaml
Add hiero-mirror-node groups
Fixes https://github.com/hiero-ledger/tsc/issues/50
> Add hiero-mirror-node groups

- config.yaml
Created hiero-protobufs groups and added Services team members
Partially fixes https://github.com/hiero-ledger/tsc/issues/41
> Add hiero-protobufs

- config.yaml
> User georgiyazovaliiski has been deleted

- config.yaml
Add maintainers and committers groups for hiero-local-node
> Add local node maintainers and committers

- config.yaml
Add Pavel to the `github-committers` group.
> Add PavelSBorisov to github-committers group

- config.yaml
Remove duplicate entry of ElijahLynn. Also exists on line 99 of the `config.yaml` file.
Fixes #80
> ci: remove duplicate user

- config.yaml
Updates config.yaml to include changes for hiero-local-node
**Related Issues**:
Fixes #86
> chore: Update config.yaml for hiero-local-node transfer

- README.md
added a small detail about temporary groups
> Minimalistic change of doc

- config.yaml
Create the `hiero-sdk-swift` repository.
Fixes #91
> ci: add hiero-sdk-swift repo

- config.yaml
Created hcn (hiero consensus node) teams for consensus maintainers/committers and tools and libraries maintainers/committers
> Update config.yaml with consensus and tools-and-libs teams

- config.yaml
Renamed groups to match the new naming convention
> Renamed hcn-execution groups

- config.yaml
Added definitions for those 2 teams.
> Update config.yaml with hiero-mirror-node-explorer-maintainers and hiero-mirror-node-explorer-committers

- config.yaml
Add the `hiero-docs` repo to config.yaml file
Fixes #112
> chore: add hiero-docs repo to config

- config.yaml
Update config.yaml with smart contract team current and honorary mentions
> Update config.yaml with smart contract team

- config.yaml
> Per shemnon

- config.yaml
Add hcn-release-managers group
> chore: Update config.yaml to add hcn-release-managers group

- config.yaml
Added hiero-consensus-node repository
> chore: Add hiero-consensus-node to CLO Warden configuration

- config.yaml
Add hiero-performance-engineers team and add to hiero-consensus-node with write permissions
> chore: Add hiero-performance-engineers team

- config.yaml
Adds hiero-mirror-node repository
Adds hiero-miorror-node-automation team
Updates hiero-mirror-node-committers
> chore: Add hiero-mirror-node to hiero-ledger

- config.yaml
Create the `hiero-block-node` repository and add teams.
Fixes #137
> chore: add hiero-block-node repository

- config.yaml
Add Jeff Morgan and a contributor for the Tools and Libraries Team
> chore:Add Jeff Morgan as committer for his team

- config.yaml
Add `hiero-sdk-rust` repository to `hiero-ledger` org.
Fixes #141
> chore: add hiero-sdk-rust repository

- config.yaml
Add Pavel to github-maintainers group
Fixes #148
> chore: add Pavel to github-maintainers group

- config.yaml
These two users can't be invited
> Elide users causing errors

- config.yaml
Create the hiero-mirror-node-explorer repo with appropriate permissions.
Fixes #158
> chore: create hiero-mirror-node-explorer repo

- config.yaml
Add hiero-automation user to the MNE repo.
Fixes #163
> chore: add hiero automation user to MNE

- config.yaml
Add jasperpotts to maintainers and committers
Fixes #
**Checklist**
> Add jasperpotts to maintainers and committers

- elections/nominees/mar-2025-election/Roger-Barker.md
Nominates Roger for the Contributor Seat as part of the march 2025 election period.
> Nominate Roger Barker for TSC Contributor Seat

- CODEOWNERS
> Update CODEOWNERS to add required reviewers

- config.yaml
Adds security-maintainers, prod-security, and sec-ops teams
> chore: Update config.yaml

- config.yaml
Updates the team names to be aligned with the new proposed name for the repository hiero-improvement-proposals**
> chore: Prepare hiero-improvement-proposals repository transfer

- elections/nominees/mar-2025-election/Tony-Camero.md
Tony Camero
Tony has been a builder and ecosystem strategist within Hedera since 2018. He is the founder of Scend Technologies, the company behind CraftTrust — a real-world deployment of decentralized payments, rewards, and stablecoin settlement serving the regulated cannabis sector. Tony has led deep integrations with Hedera-native partners such as Brale and EarthID to bring KYB/KYC, identity, and regulated stablecoins to non-custodial wallets and small business banking solutions.
Tony also leads the development of the **Scend Trust Ecosystem**, a decentralized framework designed to return control of identity, assets, and communication to individuals. Through tools like the Scend App and The Culture Wallet, Tony is focused on building usable, compliant Web3 infrastructure that empowers …
> Create End User Tony Camero

- config.yaml
Remove user edwin-greene from hiero-ledger projects
> chore: Remove user from teams

- repo-properties.yaml
Updates initial-ci-review-by-team and initial-ci-review-date for ihero-consensus-node
> chore: Set properties for HCN

- repo-properties.yaml
Update hiero-sdk-rust properties.
> chore: update repo-properties.yaml

- repo-properties.yaml
Update repo-properties.yaml for hiero-sdk-java audit completion.
> chore: update repo-properties for hiero-sdk-java

- repo-properties.yaml
Update repo-properties for hiero-sdk-js for completing repo audit.
> chore: update repo-properties for hiero-sdk-js

- config.yaml
Add user akugal to hiero-consensus-node-foundation-internal-contributors team
> chore: Update config.yaml per RESD-184

- config.yaml
Per RESD-211 initiating a vote for removal of user mgoelswirlds from the hiero-ledger organization
Each team requires 2/3rds sign-off to remove the user. The vote may pass for hiero-mirror-node-committers but may fail for hiero-improvement-proposals. Any passing vote (based on 2/3rds approval) is considered passing and the PR will be modified if needed to support the outcome of voting.
- @steven-sheehy
- @xin-hedera
- @sergmetelin
- @mgarbs
- @RaphaelMessian
- Vote by 2025-04-18
Please perform your vote by 
- Selecting the 'Request Changes' on a review to reject the vote (leaving the user in the organization) 
- Selecting 'approve pull request' on a review to approve the vote (removing the user from the organization).
Abstaining from the voting process
> chore: Update config to remove user mgoelswirlds due 2024-04-18

- config.yaml
- add solo repo to `config.yaml`
- add solo-committers to `config.yaml`
- add solo-maintainers to `config.yaml`
Fixes #
**Checklist**
> chore: add solo repo, solo-committers, and solo-maintainers to `config.yaml`

- config.yaml
Adds alex-kuzmin-hg to solo committers
> Update config.yaml for missing solo project committer

- elections/nominees/mar-2025-election/Sumabala-Nair.md
This PR is raised on behalf of Sumabala Nair
Should replace:
https://github.com/hiero-ledger/governance/pull/200
> chore: Add nomination for Sumabala Nair

- .github/PULL_REQUEST_TEMPLATE/custom_properties_update_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/new_repository_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/new_team_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/vote_pr_template.md
Adds the following PR template files:
- custom_properties_update_pr_template.md
- new_team_pr_template.md
- new_repository_pr_template.md
- vote_pr_template.md
> chore: Add PR templates to governance repository

- .github/PULL_REQUEST_TEMPLATE/custom_properties_update_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/new_repository_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/new_team_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/vote_pr_template.md
Update PR templates to include new changes to the PR so that the PR template selector appears.
> chore: Add selector info for PR templates

- .github/PULL_REQUEST_TEMPLATE/custom_properties_update_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/new_repository_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/new_team_pr_template.md
- .github/PULL_REQUEST_TEMPLATE/vote_pr_template.md
- README.md
Recerts changes to pull request templates.
#230 
We need to modify pull request URLs to create new ones using the templates.
- Org level PR template: `https://github.com/hiero-ledger/governance/compare/main...<my-branch>?quick_pull=1`
- Vote PR template: `https://github.com/hiero-ledger/governance/compare/main...<my-branch>?template=vote_pr_template.md`
- Cusom Properties PR template: `https://github.com/hiero-ledger/governance/compare/main...<my-branch>?template=custom_properties_update_pr_template.md`
- New Team PR template: `https://github.com/hiero-ledger/governance/compare/main...<my-branch>?template=new_team_pr_template.md`
- New Repository PR template: `https://github.com/hiero-ledger/governance/compare/main...<my-branch>?template=new_repositor …
> chore: revert changes from issue #230

- .github/workflows/configure-custom-properties.yaml
- .github/workflows/read-all-custom-properties.yaml
- .github/workflows/update-custom-properties.yaml
- Add self hosted runner label `hiero-governance-linux-medium`
- Add step-security harden runner action
- closes #244
> chore: Update workflows

- elections/nominees/mar-2025-election/Brandon-Davenport.md
This PR is a submission of my nomination to the Hiero TSC End User seat. After being an active participant since the beginning, I am excited to continue contributing and supporting!
Thank you for the opportunity!
> Nomination of Brandon Davenport for End User Seat

- elections/nominees/mar-2025-election/Alexander-Shenshin.md
This PR is a submission of my nomination to the Hiero TSC Contributor Seat.
Thank you for a great opportunity!
> Nomination of Alexander Shenshin for Contributor Seat

- project-rules-exceptions.md
> chore: Update project-rules-exceptions.md

- config.yaml
@cody-littley has requested to be removed from all roles in hiero-ledger. This PR does that.
Reference this [discussion](https://github.com/orgs/hiero-ledger/discussions/68#discussioncomment-13198074)
> chore: Remove user cody-littley from assigned teams

- elections/elections.md
**Description**: Fixing the link to the technical charter
> Fix link technical charter in elections.md

- config.yaml
Fixes username for clowarden
**Checklist**
> Fix HGraphPunks

- config.yaml
Reverts hiero-ledger/governance#362
accidentally merged.
> chore: add a new homebrew-solo repository for the Solo project - REVERT

- templates/project-proposal.md
Added a template for project proposals to the Hiero documentation.
> project proposal template

- committer-and-maintainer-faq.md
Committer and Maintainer FAQ added
> Committer and Maintainer FAQ

- config.yaml
Add new LF staff to LF staff role.
**Checklist**
> Add Chrissy Harter

- config.yaml
- Add: `AlexKehayov`, `renbtg` and `aderevets`
- Remove: `elpinkypie`
Fixes #
**Checklist**
> chore: Update hiero-consensus-node-internal-contributors members

- roles-and-groups.md
Additional Roles for supporting onboarding, contribution and project management
> Additional Roles for supporting onboarding & management

- config.yaml
Added members to the hiero-cli-committers group.
> Update members for hiero-cli-committers

- config.yaml
account name caps matter. neurone is not Neurone
**Checklist**
> neurone is not Neurone

- elections/nominees/sep-2025-election/README.md
Information about voting process added
> voting information for election added

- guidelines/good-first-issues.md
Added a link to view all candidates for good first issues and clarified the review process.
> Update guidelines for reviewing good first issues

- config.yaml
Create the `hiero-cli` repository.
Implements #395
> chore: create the hiero-cli repo
