hiero-ledger/governance

config.yaml

Two accounts have incorrect case.
Two accounts no longer exist.

Fix case, remove dead accounts

---

config.yaml

Adds hiero-sdk-cpp repository and hiero-sdk-tck repository through clowarden. Also adds the hiero-sdk-tck-maintainers team.

chore: Add hiero-sdk-cpp and hiero-sdk-tck repos to org

---

config.yaml

Adds the `github-committers` team; should match
`hashgraph/devops-ci-committers`. This team should get `write` permissions on all new repositories
Adds @andrewb1269hg to github-maintainers team

chore: add github-committers team

---

config.yaml

Create the `hiero-sdk-js` repository and assign teams (maintainers and committers).
Fixes #88

chore: create hiero-sdk-js repository group and assign teams

---

config.yaml

Add `andrewb1269hg` to `github-committers` group.
Fixes #127

chore: add maintainer to committer group

---

config.yaml

- With this, **hiero-gradle-conventions-maintainers** (which includes _jjohannes_) have write access for all repos that use the Gradle Conventions.
- _jjohannes_ does not need to be a direct maintainer to hiero-block-node as he already has write access through **hiero-gradle-conventions-maintainers**

chore: hiero-gradle-conventions-maintainers access sdk-java / remove jjohaness from hiero-block-node

---

config.yaml

Adds user @akdev to hcn-execution-committers

chore: add user akdev to hcn-execution-committers

---

config.yaml

Remove Mihail Mihov from hiero-block-node-committers and hiero-gradle-conventions-committers groups.
Fixes #144

chore: remove Mihail Mihov from block node and gradle conventions group

---

config.yaml

Reverts change to hcn-execution-maintainers to place user, netopyr, as the maintainer. This change occurred erroneously.
Reverts change adding akdev to hcn-execution-committers. This change occurred as part of RESD-112. RESD-111 provides additional context. User akdev will be brought back in to an internal team as part of PR #147

chore: revert accidental changes to config.yaml

---

config.yaml

Per [RESD-111](https://swirldslabs.atlassian.net/browse/RESD-111)

chore: Add team hcn-execution-internal-contributors

---

config.yaml

Per LFDT requirements each repository should have a single maintainers group to ensure a 2/3rds quorum for voting members into committer/contributor roles.

chore: Consolidate hiero-consensus-node maintainers into a single group

---

config.yaml

Add JSON RPC relay groups
List preserves maintain and committers who've made honorable commits in the past few years
Fixes [43](https://github.com/hiero-ledger/tsc/issues/43)
**Checklist**

Add JSON RPC relay groups

---

config.yaml

This PR adds the required configuration for the new Hiero Improvement Proposal repository:
- Creates `hiero-improvement-proposal-maintainers` team with EMerchant90, mgarbs, and RaphaelMessian as maintainers
- Creates `hiero-improvement-proposal-committers` team with the same maintainers plus appropriate members
- Adds repository configuration with proper team permissions
This follows the standard governance pattern established for other Hiero projects.

add maintainers and members for hiero improvement proposals

---

elections/ADOPTERS.md

This change is to bring consistency across how this file is named in other communities.

Chore: Rename "End User Electors" to "Adopters"

---

config.yaml

Create the `hiero-json-rpc-relay` repo and add teams with permissions.
Fixes #170

chore: create hiero-json-rpc-relay repo

---

config.yaml

This pull request changes the following: 
- Adds Glib and Josh to the `hcn-execution-internal-contributors` team which grants access to the `Services` project and `Triage` access to the repository.
- Closes #175 
Votes should be cast by approving (for a yes), requesting changes (for a no), or commenting (if abstaining).
Voting will close on Thursday, March 27, 2025, at 5 PM CT.

chore: add glib and josh to execution contributors team

---

config.yaml

Sets permission on repositories to `maintain` for the `github-maintainers` team across all repositories.

chore: Update permission on github-maintainers org wide

---

README.md
config.yaml

Removes the github-committers team. Follow-on to update codeowners across the hiero-ledger repos.

chore: remove github-committers team

---

config.yaml

`bibitibooo1` does not have a verified email and adding them causes errors in CLOWarden

Remove user with no verified email

---

config.yaml

A reorder of maintainers, owners, commiters, to match the existing teams, and roles
- i added the nowdays maintainers to maintainers
- Moved the ones that are not maintaining only to commiter
- Kept only 1 maintainer matching the iniatiave lead

chore: reorder json rpc group reorder

---

config.yaml

This PR is adding Nir Ben-Or's user (`nirbosl`) to the `hiero-mirror-node-committers` members list.
It is meant to grant my user a higher permission level to the `hiero-ledger/hiero-mirror-node` repository in order to be able to link my issues from the DevOps `hashgraph/infrastructure` repository kanban board to mirrornode's as I work on mirrornode related tasks.
- Add `nirbosl` to the `hiero-mirror-node-committers` member list
N/A
N/A
**Checklist**
N/A

Add nirbosl to hiero-mirror-node-committers members

---

config.yaml

Updating Smart contracts role
- Keeping David Bakin and stoqnkpL  as commiter  ( removing from maintainers )
- Adding bubo and stoyanov as maintainers, and codeowners

chore: Updating Smart contracts roles

---

config.yaml

Added repo and initial members of the committers and maintainers group.
Based on the discussion #59
Initial members suggested. Let me know if we should vote them or if we can directly add more members and leave it as a vote in this PR

Chore: Add sdk-collaboration-hub repo

---

config.yaml

Hiero-consensus-node team names have been truncated such that they are `hcn-<team-name>`. This has the potential to cause confusion.
Per the community call on 2025-04-03 the `hcn-**` teams should have names updated to reflect the repository they are contained within: `hiero-consensus-node-**`.
This PR aims to do that.

chore: Update config.yaml to change team names for hiero-consensus-node

---

config.yaml

**RESD-184**:
> Can we create 2 new groups within the governance repo, hcn-consensus-internal-contributors for triage access to the consensus team and add jeffrey-morgan34 and hcn-foundation-internal-contributors for triage access to foundation/tools & libraries and add akugal. 
> We also need to rename hcn-tools-and-libs-codeowners,  hcn-tools-and-libs-committers, and hcn-tools-and-libs-maintainers to hcn-foundation-codeowners,  hcn-foundation-committers, and hcn-foundation-maintainers,respectively
Updating governance as follows:
- hiero-consensus-node-foundation-codeowners (write)
- hiero-consensus-node-foundation-committers (write)
- hiero-consensus-node-foundation-maintainers (maintain)
- hiero-consensus-node-consensus-internal-contributors (triage)
- …

chore: Update config.yaml per RESD-184

---

config.yaml

Due to lack of response to invitations, we need to remove this group. Triage of the hiero-website and awesome-contributions repo will be done by other assigned teams.
The community is always welcomed to participate by contribuiting to any repo via PR.

Chore: Remove community group from config.yaml

---

config.yaml

Adds the `solo-admins` team
See [RESD-225](https://swirldslabs.atlassian.net/servicedesk/customer/portal/7/RESD-225)
closes #223

chore: Update config.yaml to add solo-admins team

---

config.yaml

This PR adds gsstoykov as a Rust SDK maintainer

chore: propose gsstoykov Rust SDK maintainer

---

config.yaml

Add maintainer groups to the governance repo with `triage` permissions so that maintainers can create PRs with labels & request reviews on those PRs.

chore: Update config.yaml to add maintainers groups to governance (triage)

---

config.yaml

This pull request changes the following:
- Adds `timfn-hg` to the `hiero-consensus-node-execution-committers`, `hiero-consensus-node-execution-codeowners` teams which grants access to the `hiero-consensus-node-execution` project.
- Removes `timfn-hg` from the `hiero-consensus-node-consensus-committers, `hiero-consensus-node-consensus-codeowners` teams which revokes access to the `hiero-consensus-node-consensus` project.
- closes #153
Per the guidelines outlined in the `roles-and-groups.md` in this repository votes should be cast as follows:
- Vote <span style="color:green">**in favor**</span> of the candidate's promotion by **approving** the PR with a **comment indicating approval**.
- Vote <span style="color:red">**against**</span> the candidate's promotion by **posting a comment in the …

chore: Move Tim Farber-Newman

---

config.yaml

Removes the following people from the `hiero-consensus-node-consensus-codeowners` group per their request:
- @mustafauzunn
- @IvanKavaldzhiev
- @edward-swirldslabs 
**Voting is required**
Per the guidelines outlined in the roles-and-groups.md in this repository votes should be cast as follows:
• Vote in favor of the candidate's promotion by approving the PR with a comment indicating approval.
• Vote against the candidate's promotion by posting a comment in the PR along with their explanation.
• Vote to abstain by posting a comment in the PR along with their explanation.
**Voting Period**
The vote will close on Wednesday 16th July at 23:59:00 CEST

chore: Remove Ed, Mustafa, and Ivan K from consensus module code owners

---

config.yaml

This pull request changes the following:
- Adds `rbair123` and `jasperpotts` to the `hiero-consensus-node-maintainers` team which grants access to the
`hiero-consensus-node` project and `maintain` access to the repository.
- closes #351
Per the guidelines outlined in the `roles-and-groups.md` in this repository votes should be cast as follows:
- Vote <span style="color:green">**in favor**</span> of the candidate's promotion by **approving** the PR with a **comment indicating approval**.
- Vote <span style="color:red">**against**</span> the candidate's promotion by **posting a comment in the PR along with their explanation**.
- Vote <span style="color:orange">**to abstain**</span> by **posting a comment in the PR along with their explanation**.
The vote will close on `Monday, July 28, …

chore: Update Consensus Node Maintainers

---

config.yaml

This pull request adds a new repository configuration to the `config.yaml` file. The update introduces the `homebrew-solo` repository and assigns appropriate team permissions.
Repository configuration changes:
* Added the `homebrew-solo` repository with specified team permissions and set its visibility to public.
This repository is needed to support [Homebrew Taps](https://docs.brew.sh/Taps) for the Solo project. This repository is a hard requirement from Homebrew in order to support the `brew tap hiero-ledger/solo` syntax. Please see the documentation snippet below.
- required by: https://github.com/hiero-ledger/solo/issues/1001

chore: add a new homebrew-solo repository for the Solo project

---

config.yaml

Adds triage permissions to `hiero-sdk-[js|tck]-internal-contributors` teams

chore: Add triage permission for internal contributors

---

config.yaml

Nominating `exploreriii` as python sdk maintainer
Moving `hendrikebbers` from maintainer to committers
@nadineloepfe @rbair23 can you please approve?

Nominating exploreriii as python sdk maintainer

---

config.yaml

This pull request changes the following:
- Adds `mustafauzunn` to the `hiero-block-node-committers` team which grants access to the [Block Node Repo](https://github.com/hiero-ledger/hiero-block-node) project and write access to the repository.
- Removes `mattp-swirldslabs` from the `hiero-block-node-maintainers` team which governs maintainer role for the [Block Node Repo](https://github.com/hiero-ledger/hiero-block-node).
Fixes #374 
Per the guidelines outlined in the `roles-and-groups.md` in this repository votes should be cast as follows:
- Vote <span style="color:green">**in favor**</span> of the candidate's promotion by **approving** the PR with a **comment indicating approval**.
- Vote <span style="color:red">**against**</span> the candidate's …

Update BN committers (add mustafauzunn) and maintainers (remove mattp-swirldslabs)

---

config.yaml

Add `devmab` to `hiero-cli-committers` group.
Implements #397

chore: add devmab to hiero-cli-committers group
